FROM nginx:alpine

# Uygulama dosyalarını Nginx'in varsayılan statik dosya dizinine kopyala
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/

EXPOSE 80
